[install]
# Only install package versions published at least 3 days ago
minimumReleaseAge = 432000 # 5 Days: 5 * 86,400 = 432,000 seconds.

[install.security]
scanner = "@socketsecurity/bun-security-scanner"
