# Use the APP_VERSION build argument if passed
ARG APP_VERSION=0.0.0

# use the official Bun image
# see all versions at https://hub.docker.com/r/oven/bun/tags
FROM oven/bun:1 AS base
WORKDIR /usr/src/app

# install dependencies into temp directory
# this will cache them and speed up future builds
FROM base AS install

RUN mkdir -p /temp/dev
COPY package.json bun.lock /temp/dev/
RUN cd /temp/dev && bun install --frozen-lockfile

# install with --production (exclude devDependencies)
RUN mkdir -p /temp/prod
COPY package.json bun.lock /temp/prod/
RUN cd /temp/prod && bun install --frozen-lockfile --ignore-scripts --production

# copy node_modules from temp directory
# then copy all (non-ignored) project files into the image
FROM base AS prerelease
COPY --from=install /temp/dev/node_modules node_modules
COPY . .

# [optional] tests & build
#ENV NODE_ENV=production
#RUN bun test
RUN bun run make

# copy production dependencies and source code into final image
FROM base AS release
COPY --from=prerelease /usr/src/app/package.json .
COPY --from=prerelease /usr/src/app/.output .
RUN rm -rf ./server/node_modules/
COPY --from=install /temp/prod/node_modules ./server/node_modules/

# run the app
USER bun
EXPOSE 8088/tcp
ENV NODE_ENV=production
WORKDIR /usr/src/app/server
ENTRYPOINT [ "bun", "run", "index.mjs" ]
