import { type Response } from 'redaxios';
import { OuterError } from '~/base/utils/outer-error';
import { type UserReportableErrorsType, userReportableErrorsSchema } from '../schema/user-reportable-errors';

/**
 * An error class that takes an array of user reproducible errors, passed
 * from the client and concatenates them into one string. Generated by
 * checkResultAndThrowIfErrorIsSpecial
 */
export class UserReportableErrorsError extends Error {
  errors: UserReportableErrorsType;

  constructor(errors: UserReportableErrorsType) {
    super(errors.map((err) => err.message).join(', because: '));
    this.errors = errors;
  }
}

/**
 * Validation for axios. It allows for all success codes and 422, which
 * is used by the server to return user reportable errors.
 * @param status The HTTP status code
 * @returns void
 */
export function validateStatus(status: number) {
  return (
    (status >= 200 && status < 300) || // Success codes
    status === 422 // Unprocessable Entity
  );
}

/**
 * Checks if the server returned error status code 422 (used for user
 * reportable errors) and retrieves the user reportable error and generates
 * UserReportableErrorsError.
 * @param result Axios result
 */
export function checkResultAndThrowIfErrorIsSpecial<T>(result: Response<T>) {
  if (result.status === 422) {
    // biome-ignore lint/suspicious/noExplicitAny: Temporary
    const errorResponseJson: any = result.data;

    if (errorResponseJson.userReportableErrors) {
      const userReportableErrorsResult = userReportableErrorsSchema.safeParse(errorResponseJson.userReportableErrors);
      if (userReportableErrorsResult.success) {
        throw new UserReportableErrorsError(errorResponseJson.userReportableErrors);
      }
    }
  }
}

/**
 * Throw a well formatted error that can be later displayed in a user
 * friendly way
 * @param verb HTTP verb - DELETE, GET, POST, PUT
 * @param err The error that occurred
 * @param queryString Query string of the request
 * @param dataAsStr Data passed with the request - null for GET
 */
export function processAxiosOrSpecialException(
  verb: 'DELETE' | 'GET' | 'POST' | 'PUT',
  // biome-ignore lint/suspicious/noExplicitAny: catch will catch any error
  err: any,
  queryString: string,
  dataAsStr: string | null
) {
  console.error('queryFnGet:', err);

  // Do not wrap user reportable errors since they already contain all the infromation
  if (err instanceof UserReportableErrorsError) {
    throw err;
  }

  throw new OuterError(`Failed to ${verb}, query string: [${queryString}  ], data: [${dataAsStr}]`, err);
}
