/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as authPagesRouteRouteImport } from './routes/(auth-pages)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authPagesSignupRouteImport } from './routes/(auth-pages)/signup'
import { Route as authPagesLoginRouteImport } from './routes/(auth-pages)/login'
import { Route as authenticatedDashboardRouteRouteImport } from './routes/(authenticated)/dashboard/route'
import { Route as authenticatedDashboardIndexRouteImport } from './routes/(authenticated)/dashboard/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as authenticatedDashboardAdminIndexRouteImport } from './routes/(authenticated)/dashboard/admin/index'
import { Route as authenticatedDashboardAccountIndexRouteImport } from './routes/(authenticated)/dashboard/account/index'
import { Route as authenticatedDashboardTanstartEddyExamplesExampleLayout6RouteImport } from './routes/(authenticated)/dashboard/tanstart-eddy-examples/example-layout-6'
import { Route as authenticatedDashboardTanstartEddyExamplesExampleLayout5RouteImport } from './routes/(authenticated)/dashboard/tanstart-eddy-examples/example-layout-5'
import { Route as authenticatedDashboardTanstartEddyExamplesExampleLayout4RouteImport } from './routes/(authenticated)/dashboard/tanstart-eddy-examples/example-layout-4'
import { Route as authenticatedDashboardTanstartCumberlandExamplesExampleLayout3RouteImport } from './routes/(authenticated)/dashboard/tanstart-cumberland-examples/example-layout-3'
import { Route as authenticatedDashboardTanstartCumberlandExamplesExampleLayout2RouteImport } from './routes/(authenticated)/dashboard/tanstart-cumberland-examples/example-layout-2'
import { Route as authenticatedDashboardTanstartCumberlandExamplesExampleLayout1RouteImport } from './routes/(authenticated)/dashboard/tanstart-cumberland-examples/example-layout-1'
import { Route as authenticatedDashboardAdminUsersRouteImport } from './routes/(authenticated)/dashboard/admin/users'
import { Route as ApiV1TanstartEddyExamplesHorsesIndexRouteImport } from './routes/api/v1/tanstart-eddy-examples/horses/index'
import { Route as ApiV1SystemGlobalClientSettingsIndexRouteImport } from './routes/api/v1/system/global-client-settings/index'
import { Route as ApiV1SystemAboutIndexRouteImport } from './routes/api/v1/system/about/index'
import { Route as ApiV1TanstartEddyExamplesHorsesIdRouteImport } from './routes/api/v1/tanstart-eddy-examples/horses/$id'
import { Route as authenticatedDashboardTanstartEddyExamplesHorsesHorseListRouteImport } from './routes/(authenticated)/dashboard/tanstart-eddy-examples/horses/horse-list'

const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authPagesRouteRoute = authPagesRouteRouteImport.update({
  id: '/(auth-pages)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authPagesSignupRoute = authPagesSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const authPagesLoginRoute = authPagesLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const authenticatedDashboardRouteRoute =
  authenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedDashboardIndexRoute =
  authenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedDashboardAdminIndexRoute =
  authenticatedDashboardAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardAccountIndexRoute =
  authenticatedDashboardAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardTanstartEddyExamplesExampleLayout6Route =
  authenticatedDashboardTanstartEddyExamplesExampleLayout6RouteImport.update({
    id: '/tanstart-eddy-examples/example-layout-6',
    path: '/tanstart-eddy-examples/example-layout-6',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardTanstartEddyExamplesExampleLayout5Route =
  authenticatedDashboardTanstartEddyExamplesExampleLayout5RouteImport.update({
    id: '/tanstart-eddy-examples/example-layout-5',
    path: '/tanstart-eddy-examples/example-layout-5',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardTanstartEddyExamplesExampleLayout4Route =
  authenticatedDashboardTanstartEddyExamplesExampleLayout4RouteImport.update({
    id: '/tanstart-eddy-examples/example-layout-4',
    path: '/tanstart-eddy-examples/example-layout-4',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardTanstartCumberlandExamplesExampleLayout3Route =
  authenticatedDashboardTanstartCumberlandExamplesExampleLayout3RouteImport.update(
    {
      id: '/tanstart-cumberland-examples/example-layout-3',
      path: '/tanstart-cumberland-examples/example-layout-3',
      getParentRoute: () => authenticatedDashboardRouteRoute,
    } as any,
  )
const authenticatedDashboardTanstartCumberlandExamplesExampleLayout2Route =
  authenticatedDashboardTanstartCumberlandExamplesExampleLayout2RouteImport.update(
    {
      id: '/tanstart-cumberland-examples/example-layout-2',
      path: '/tanstart-cumberland-examples/example-layout-2',
      getParentRoute: () => authenticatedDashboardRouteRoute,
    } as any,
  )
const authenticatedDashboardTanstartCumberlandExamplesExampleLayout1Route =
  authenticatedDashboardTanstartCumberlandExamplesExampleLayout1RouteImport.update(
    {
      id: '/tanstart-cumberland-examples/example-layout-1',
      path: '/tanstart-cumberland-examples/example-layout-1',
      getParentRoute: () => authenticatedDashboardRouteRoute,
    } as any,
  )
const authenticatedDashboardAdminUsersRoute =
  authenticatedDashboardAdminUsersRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const ApiV1TanstartEddyExamplesHorsesIndexRoute =
  ApiV1TanstartEddyExamplesHorsesIndexRouteImport.update({
    id: '/api/v1/tanstart-eddy-examples/horses/',
    path: '/api/v1/tanstart-eddy-examples/horses/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1SystemGlobalClientSettingsIndexRoute =
  ApiV1SystemGlobalClientSettingsIndexRouteImport.update({
    id: '/api/v1/system/global-client-settings/',
    path: '/api/v1/system/global-client-settings/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1SystemAboutIndexRoute = ApiV1SystemAboutIndexRouteImport.update({
  id: '/api/v1/system/about/',
  path: '/api/v1/system/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TanstartEddyExamplesHorsesIdRoute =
  ApiV1TanstartEddyExamplesHorsesIdRouteImport.update({
    id: '/api/v1/tanstart-eddy-examples/horses/$id',
    path: '/api/v1/tanstart-eddy-examples/horses/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const authenticatedDashboardTanstartEddyExamplesHorsesHorseListRoute =
  authenticatedDashboardTanstartEddyExamplesHorsesHorseListRouteImport.update({
    id: '/tanstart-eddy-examples/horses/horse-list',
    path: '/tanstart-eddy-examples/horses/horse-list',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof authenticatedDashboardRouteRouteWithChildren
  '/login': typeof authPagesLoginRoute
  '/signup': typeof authPagesSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/': typeof authenticatedDashboardIndexRoute
  '/dashboard/admin/users': typeof authenticatedDashboardAdminUsersRoute
  '/dashboard/tanstart-cumberland-examples/example-layout-1': typeof authenticatedDashboardTanstartCumberlandExamplesExampleLayout1Route
  '/dashboard/tanstart-cumberland-examples/example-layout-2': typeof authenticatedDashboardTanstartCumberlandExamplesExampleLayout2Route
  '/dashboard/tanstart-cumberland-examples/example-layout-3': typeof authenticatedDashboardTanstartCumberlandExamplesExampleLayout3Route
  '/dashboard/tanstart-eddy-examples/example-layout-4': typeof authenticatedDashboardTanstartEddyExamplesExampleLayout4Route
  '/dashboard/tanstart-eddy-examples/example-layout-5': typeof authenticatedDashboardTanstartEddyExamplesExampleLayout5Route
  '/dashboard/tanstart-eddy-examples/example-layout-6': typeof authenticatedDashboardTanstartEddyExamplesExampleLayout6Route
  '/dashboard/account/': typeof authenticatedDashboardAccountIndexRoute
  '/dashboard/admin/': typeof authenticatedDashboardAdminIndexRoute
  '/dashboard/tanstart-eddy-examples/horses/horse-list': typeof authenticatedDashboardTanstartEddyExamplesHorsesHorseListRoute
  '/api/v1/tanstart-eddy-examples/horses/$id': typeof ApiV1TanstartEddyExamplesHorsesIdRoute
  '/api/v1/system/about/': typeof ApiV1SystemAboutIndexRoute
  '/api/v1/system/global-client-settings/': typeof ApiV1SystemGlobalClientSettingsIndexRoute
  '/api/v1/tanstart-eddy-examples/horses/': typeof ApiV1TanstartEddyExamplesHorsesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authPagesLoginRoute
  '/signup': typeof authPagesSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof authenticatedDashboardIndexRoute
  '/dashboard/admin/users': typeof authenticatedDashboardAdminUsersRoute
  '/dashboard/tanstart-cumberland-examples/example-layout-1': typeof authenticatedDashboardTanstartCumberlandExamplesExampleLayout1Route
  '/dashboard/tanstart-cumberland-examples/example-layout-2': typeof authenticatedDashboardTanstartCumberlandExamplesExampleLayout2Route
  '/dashboard/tanstart-cumberland-examples/example-layout-3': typeof authenticatedDashboardTanstartCumberlandExamplesExampleLayout3Route
  '/dashboard/tanstart-eddy-examples/example-layout-4': typeof authenticatedDashboardTanstartEddyExamplesExampleLayout4Route
  '/dashboard/tanstart-eddy-examples/example-layout-5': typeof authenticatedDashboardTanstartEddyExamplesExampleLayout5Route
  '/dashboard/tanstart-eddy-examples/example-layout-6': typeof authenticatedDashboardTanstartEddyExamplesExampleLayout6Route
  '/dashboard/account': typeof authenticatedDashboardAccountIndexRoute
  '/dashboard/admin': typeof authenticatedDashboardAdminIndexRoute
  '/dashboard/tanstart-eddy-examples/horses/horse-list': typeof authenticatedDashboardTanstartEddyExamplesHorsesHorseListRoute
  '/api/v1/tanstart-eddy-examples/horses/$id': typeof ApiV1TanstartEddyExamplesHorsesIdRoute
  '/api/v1/system/about': typeof ApiV1SystemAboutIndexRoute
  '/api/v1/system/global-client-settings': typeof ApiV1SystemGlobalClientSettingsIndexRoute
  '/api/v1/tanstart-eddy-examples/horses': typeof ApiV1TanstartEddyExamplesHorsesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth-pages)': typeof authPagesRouteRouteWithChildren
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(authenticated)/dashboard': typeof authenticatedDashboardRouteRouteWithChildren
  '/(auth-pages)/login': typeof authPagesLoginRoute
  '/(auth-pages)/signup': typeof authPagesSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(authenticated)/dashboard/': typeof authenticatedDashboardIndexRoute
  '/(authenticated)/dashboard/admin/users': typeof authenticatedDashboardAdminUsersRoute
  '/(authenticated)/dashboard/tanstart-cumberland-examples/example-layout-1': typeof authenticatedDashboardTanstartCumberlandExamplesExampleLayout1Route
  '/(authenticated)/dashboard/tanstart-cumberland-examples/example-layout-2': typeof authenticatedDashboardTanstartCumberlandExamplesExampleLayout2Route
  '/(authenticated)/dashboard/tanstart-cumberland-examples/example-layout-3': typeof authenticatedDashboardTanstartCumberlandExamplesExampleLayout3Route
  '/(authenticated)/dashboard/tanstart-eddy-examples/example-layout-4': typeof authenticatedDashboardTanstartEddyExamplesExampleLayout4Route
  '/(authenticated)/dashboard/tanstart-eddy-examples/example-layout-5': typeof authenticatedDashboardTanstartEddyExamplesExampleLayout5Route
  '/(authenticated)/dashboard/tanstart-eddy-examples/example-layout-6': typeof authenticatedDashboardTanstartEddyExamplesExampleLayout6Route
  '/(authenticated)/dashboard/account/': typeof authenticatedDashboardAccountIndexRoute
  '/(authenticated)/dashboard/admin/': typeof authenticatedDashboardAdminIndexRoute
  '/(authenticated)/dashboard/tanstart-eddy-examples/horses/horse-list': typeof authenticatedDashboardTanstartEddyExamplesHorsesHorseListRoute
  '/api/v1/tanstart-eddy-examples/horses/$id': typeof ApiV1TanstartEddyExamplesHorsesIdRoute
  '/api/v1/system/about/': typeof ApiV1SystemAboutIndexRoute
  '/api/v1/system/global-client-settings/': typeof ApiV1SystemGlobalClientSettingsIndexRoute
  '/api/v1/tanstart-eddy-examples/horses/': typeof ApiV1TanstartEddyExamplesHorsesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/api/auth/$'
    | '/dashboard/'
    | '/dashboard/admin/users'
    | '/dashboard/tanstart-cumberland-examples/example-layout-1'
    | '/dashboard/tanstart-cumberland-examples/example-layout-2'
    | '/dashboard/tanstart-cumberland-examples/example-layout-3'
    | '/dashboard/tanstart-eddy-examples/example-layout-4'
    | '/dashboard/tanstart-eddy-examples/example-layout-5'
    | '/dashboard/tanstart-eddy-examples/example-layout-6'
    | '/dashboard/account/'
    | '/dashboard/admin/'
    | '/dashboard/tanstart-eddy-examples/horses/horse-list'
    | '/api/v1/tanstart-eddy-examples/horses/$id'
    | '/api/v1/system/about/'
    | '/api/v1/system/global-client-settings/'
    | '/api/v1/tanstart-eddy-examples/horses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/api/auth/$'
    | '/dashboard'
    | '/dashboard/admin/users'
    | '/dashboard/tanstart-cumberland-examples/example-layout-1'
    | '/dashboard/tanstart-cumberland-examples/example-layout-2'
    | '/dashboard/tanstart-cumberland-examples/example-layout-3'
    | '/dashboard/tanstart-eddy-examples/example-layout-4'
    | '/dashboard/tanstart-eddy-examples/example-layout-5'
    | '/dashboard/tanstart-eddy-examples/example-layout-6'
    | '/dashboard/account'
    | '/dashboard/admin'
    | '/dashboard/tanstart-eddy-examples/horses/horse-list'
    | '/api/v1/tanstart-eddy-examples/horses/$id'
    | '/api/v1/system/about'
    | '/api/v1/system/global-client-settings'
    | '/api/v1/tanstart-eddy-examples/horses'
  id:
    | '__root__'
    | '/'
    | '/(auth-pages)'
    | '/(authenticated)'
    | '/(authenticated)/dashboard'
    | '/(auth-pages)/login'
    | '/(auth-pages)/signup'
    | '/api/auth/$'
    | '/(authenticated)/dashboard/'
    | '/(authenticated)/dashboard/admin/users'
    | '/(authenticated)/dashboard/tanstart-cumberland-examples/example-layout-1'
    | '/(authenticated)/dashboard/tanstart-cumberland-examples/example-layout-2'
    | '/(authenticated)/dashboard/tanstart-cumberland-examples/example-layout-3'
    | '/(authenticated)/dashboard/tanstart-eddy-examples/example-layout-4'
    | '/(authenticated)/dashboard/tanstart-eddy-examples/example-layout-5'
    | '/(authenticated)/dashboard/tanstart-eddy-examples/example-layout-6'
    | '/(authenticated)/dashboard/account/'
    | '/(authenticated)/dashboard/admin/'
    | '/(authenticated)/dashboard/tanstart-eddy-examples/horses/horse-list'
    | '/api/v1/tanstart-eddy-examples/horses/$id'
    | '/api/v1/system/about/'
    | '/api/v1/system/global-client-settings/'
    | '/api/v1/tanstart-eddy-examples/horses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authPagesRouteRoute: typeof authPagesRouteRouteWithChildren
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1TanstartEddyExamplesHorsesIdRoute: typeof ApiV1TanstartEddyExamplesHorsesIdRoute
  ApiV1SystemAboutIndexRoute: typeof ApiV1SystemAboutIndexRoute
  ApiV1SystemGlobalClientSettingsIndexRoute: typeof ApiV1SystemGlobalClientSettingsIndexRoute
  ApiV1TanstartEddyExamplesHorsesIndexRoute: typeof ApiV1TanstartEddyExamplesHorsesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth-pages)': {
      id: '/(auth-pages)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authPagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth-pages)/signup': {
      id: '/(auth-pages)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authPagesSignupRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/(auth-pages)/login': {
      id: '/(auth-pages)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authPagesLoginRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/(authenticated)/dashboard': {
      id: '/(authenticated)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authenticatedDashboardRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/dashboard/': {
      id: '/(authenticated)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof authenticatedDashboardIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/dashboard/admin/': {
      id: '/(authenticated)/dashboard/admin/'
      path: '/admin'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof authenticatedDashboardAdminIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/account/': {
      id: '/(authenticated)/dashboard/account/'
      path: '/account'
      fullPath: '/dashboard/account/'
      preLoaderRoute: typeof authenticatedDashboardAccountIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/tanstart-eddy-examples/example-layout-6': {
      id: '/(authenticated)/dashboard/tanstart-eddy-examples/example-layout-6'
      path: '/tanstart-eddy-examples/example-layout-6'
      fullPath: '/dashboard/tanstart-eddy-examples/example-layout-6'
      preLoaderRoute: typeof authenticatedDashboardTanstartEddyExamplesExampleLayout6RouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/tanstart-eddy-examples/example-layout-5': {
      id: '/(authenticated)/dashboard/tanstart-eddy-examples/example-layout-5'
      path: '/tanstart-eddy-examples/example-layout-5'
      fullPath: '/dashboard/tanstart-eddy-examples/example-layout-5'
      preLoaderRoute: typeof authenticatedDashboardTanstartEddyExamplesExampleLayout5RouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/tanstart-eddy-examples/example-layout-4': {
      id: '/(authenticated)/dashboard/tanstart-eddy-examples/example-layout-4'
      path: '/tanstart-eddy-examples/example-layout-4'
      fullPath: '/dashboard/tanstart-eddy-examples/example-layout-4'
      preLoaderRoute: typeof authenticatedDashboardTanstartEddyExamplesExampleLayout4RouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/tanstart-cumberland-examples/example-layout-3': {
      id: '/(authenticated)/dashboard/tanstart-cumberland-examples/example-layout-3'
      path: '/tanstart-cumberland-examples/example-layout-3'
      fullPath: '/dashboard/tanstart-cumberland-examples/example-layout-3'
      preLoaderRoute: typeof authenticatedDashboardTanstartCumberlandExamplesExampleLayout3RouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/tanstart-cumberland-examples/example-layout-2': {
      id: '/(authenticated)/dashboard/tanstart-cumberland-examples/example-layout-2'
      path: '/tanstart-cumberland-examples/example-layout-2'
      fullPath: '/dashboard/tanstart-cumberland-examples/example-layout-2'
      preLoaderRoute: typeof authenticatedDashboardTanstartCumberlandExamplesExampleLayout2RouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/tanstart-cumberland-examples/example-layout-1': {
      id: '/(authenticated)/dashboard/tanstart-cumberland-examples/example-layout-1'
      path: '/tanstart-cumberland-examples/example-layout-1'
      fullPath: '/dashboard/tanstart-cumberland-examples/example-layout-1'
      preLoaderRoute: typeof authenticatedDashboardTanstartCumberlandExamplesExampleLayout1RouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/admin/users': {
      id: '/(authenticated)/dashboard/admin/users'
      path: '/admin/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof authenticatedDashboardAdminUsersRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/api/v1/tanstart-eddy-examples/horses/': {
      id: '/api/v1/tanstart-eddy-examples/horses/'
      path: '/api/v1/tanstart-eddy-examples/horses'
      fullPath: '/api/v1/tanstart-eddy-examples/horses/'
      preLoaderRoute: typeof ApiV1TanstartEddyExamplesHorsesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/system/global-client-settings/': {
      id: '/api/v1/system/global-client-settings/'
      path: '/api/v1/system/global-client-settings'
      fullPath: '/api/v1/system/global-client-settings/'
      preLoaderRoute: typeof ApiV1SystemGlobalClientSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/system/about/': {
      id: '/api/v1/system/about/'
      path: '/api/v1/system/about'
      fullPath: '/api/v1/system/about/'
      preLoaderRoute: typeof ApiV1SystemAboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/tanstart-eddy-examples/horses/$id': {
      id: '/api/v1/tanstart-eddy-examples/horses/$id'
      path: '/api/v1/tanstart-eddy-examples/horses/$id'
      fullPath: '/api/v1/tanstart-eddy-examples/horses/$id'
      preLoaderRoute: typeof ApiV1TanstartEddyExamplesHorsesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/dashboard/tanstart-eddy-examples/horses/horse-list': {
      id: '/(authenticated)/dashboard/tanstart-eddy-examples/horses/horse-list'
      path: '/tanstart-eddy-examples/horses/horse-list'
      fullPath: '/dashboard/tanstart-eddy-examples/horses/horse-list'
      preLoaderRoute: typeof authenticatedDashboardTanstartEddyExamplesHorsesHorseListRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
  }
}

interface authPagesRouteRouteChildren {
  authPagesLoginRoute: typeof authPagesLoginRoute
  authPagesSignupRoute: typeof authPagesSignupRoute
}

const authPagesRouteRouteChildren: authPagesRouteRouteChildren = {
  authPagesLoginRoute: authPagesLoginRoute,
  authPagesSignupRoute: authPagesSignupRoute,
}

const authPagesRouteRouteWithChildren = authPagesRouteRoute._addFileChildren(
  authPagesRouteRouteChildren,
)

interface authenticatedDashboardRouteRouteChildren {
  authenticatedDashboardIndexRoute: typeof authenticatedDashboardIndexRoute
  authenticatedDashboardAdminUsersRoute: typeof authenticatedDashboardAdminUsersRoute
  authenticatedDashboardTanstartCumberlandExamplesExampleLayout1Route: typeof authenticatedDashboardTanstartCumberlandExamplesExampleLayout1Route
  authenticatedDashboardTanstartCumberlandExamplesExampleLayout2Route: typeof authenticatedDashboardTanstartCumberlandExamplesExampleLayout2Route
  authenticatedDashboardTanstartCumberlandExamplesExampleLayout3Route: typeof authenticatedDashboardTanstartCumberlandExamplesExampleLayout3Route
  authenticatedDashboardTanstartEddyExamplesExampleLayout4Route: typeof authenticatedDashboardTanstartEddyExamplesExampleLayout4Route
  authenticatedDashboardTanstartEddyExamplesExampleLayout5Route: typeof authenticatedDashboardTanstartEddyExamplesExampleLayout5Route
  authenticatedDashboardTanstartEddyExamplesExampleLayout6Route: typeof authenticatedDashboardTanstartEddyExamplesExampleLayout6Route
  authenticatedDashboardAccountIndexRoute: typeof authenticatedDashboardAccountIndexRoute
  authenticatedDashboardAdminIndexRoute: typeof authenticatedDashboardAdminIndexRoute
  authenticatedDashboardTanstartEddyExamplesHorsesHorseListRoute: typeof authenticatedDashboardTanstartEddyExamplesHorsesHorseListRoute
}

const authenticatedDashboardRouteRouteChildren: authenticatedDashboardRouteRouteChildren =
  {
    authenticatedDashboardIndexRoute: authenticatedDashboardIndexRoute,
    authenticatedDashboardAdminUsersRoute:
      authenticatedDashboardAdminUsersRoute,
    authenticatedDashboardTanstartCumberlandExamplesExampleLayout1Route:
      authenticatedDashboardTanstartCumberlandExamplesExampleLayout1Route,
    authenticatedDashboardTanstartCumberlandExamplesExampleLayout2Route:
      authenticatedDashboardTanstartCumberlandExamplesExampleLayout2Route,
    authenticatedDashboardTanstartCumberlandExamplesExampleLayout3Route:
      authenticatedDashboardTanstartCumberlandExamplesExampleLayout3Route,
    authenticatedDashboardTanstartEddyExamplesExampleLayout4Route:
      authenticatedDashboardTanstartEddyExamplesExampleLayout4Route,
    authenticatedDashboardTanstartEddyExamplesExampleLayout5Route:
      authenticatedDashboardTanstartEddyExamplesExampleLayout5Route,
    authenticatedDashboardTanstartEddyExamplesExampleLayout6Route:
      authenticatedDashboardTanstartEddyExamplesExampleLayout6Route,
    authenticatedDashboardAccountIndexRoute:
      authenticatedDashboardAccountIndexRoute,
    authenticatedDashboardAdminIndexRoute:
      authenticatedDashboardAdminIndexRoute,
    authenticatedDashboardTanstartEddyExamplesHorsesHorseListRoute:
      authenticatedDashboardTanstartEddyExamplesHorsesHorseListRoute,
  }

const authenticatedDashboardRouteRouteWithChildren =
  authenticatedDashboardRouteRoute._addFileChildren(
    authenticatedDashboardRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedDashboardRouteRoute: typeof authenticatedDashboardRouteRouteWithChildren
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedDashboardRouteRoute:
    authenticatedDashboardRouteRouteWithChildren,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authPagesRouteRoute: authPagesRouteRouteWithChildren,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1TanstartEddyExamplesHorsesIdRoute:
    ApiV1TanstartEddyExamplesHorsesIdRoute,
  ApiV1SystemAboutIndexRoute: ApiV1SystemAboutIndexRoute,
  ApiV1SystemGlobalClientSettingsIndexRoute:
    ApiV1SystemGlobalClientSettingsIndexRoute,
  ApiV1TanstartEddyExamplesHorsesIndexRoute:
    ApiV1TanstartEddyExamplesHorsesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
